### ISSUE TITLE
REGARDING  STYLE.CSS 

### ISSUE THREAD

**Issue by binitworld** [binitworld/Shop-Sphere#4]
# ShopSphere

## Styling Changes in `style.css`

The following changes have been made in the `style.css` file:

1. **Padding Order Correction:**
   - The `padding` in the CSS file has been updated to ensure the correct order.
2. **Logo Placement:**
   - The `logo` has been repositioned to be on the right side.
3. **Navbar Position:**
   - The  `navigation bar-'contents'` has been adjusted to be on the right side.
4. **Welcome Text Centering:**
   - The text welcoming users has been centered.

## Tasks Assigned
The following tasks have been assigned to specific contributors:
- **[@eksha-malhotra](https://github.com/eksha-malhotra)**
- **[@sreevardhan-reddy](https://github.com/sreevardhan-reddy)**
Feel free to check the [style.css](/path/to/style.css) file for detailed changing

Thanks!

**Comment by sreevardhan-reddy** [comment]
I have made the changes

**Comment by binitworld** [comment]
Well Done Vardhan  @eksha-malhotra  please review the task Has the issue been resolved?

**Comment by binitworld** [comment]
ComplEted 💯

**Comment by binitworld** [comment]
No need now
